### ISSUE TITLE
Broken links on bolajiayodeji.com

### ISSUE THREAD

**Issue by spekulatius** [BolajiAyodeji/awesome-jamstack#15]
Hey @BolajiAyodeji 

looks like there are still some broken links in the list to articles from your old(?) website `bolajiayodeji.com`. Just thought I let you know.

Cheers,
Peter

**Comment by BolajiAyodeji** [comment]
Hi @spekulatius, apologies for the very delayed response. I have fixed this now, thanks.

**Comment by spekulatius** [comment]
No worries @BolajiAyodeji
